name: Generate GitHub Metrics

on:
  schedule: [{cron: "0 */6 * * *"}]  # Every 6 hours
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: securitysteven
          config_timezone: America/New_York
          config_display: large
          config_twemoji: yes
          config_animated: yes
          config_gemoji: yes
          config_octicon: yes
          config_padding: 0, 10
          base: header, activity, community, repositories
          template: classic

          plugin_languages: yes
          plugin_languages.colors: github
          plugin_languages.threshold: 2%
          plugin_languages.indepth: yes
          plugin_languages.limit: 10

          plugin_achievements: yes
          plugin_achievements.threshold: X
          plugin_achievements.display: compact
          plugin_achievements.secrets: yes
          plugin_achievements.limit: 0

          plugin_notable: yes
          plugin_notable.from: all
          plugin_notable.repositories: 5

          plugin_isocalendar: yes

          plugin_activity: yes
          plugin_activity.limit: 5
          plugin_activity.load: 300
          plugin_activity.visibility: all

          plugin_stars: yes
          plugin_stars.limit: 4

          plugin_people: yes
          plugin_people.limit: 10
          plugin_people.size: 28
          plugin_people.types: followers

          plugin_reactions: yes
          plugin_reactions.display: top
          plugin_reactions.limit: 100

          plugin_topics: yes
          plugin_topics.mode: icons
          plugin_topics.limit: 12

          plugin_copilot: yes
